name: Auto Release

on:
  push:
    branches:
      - master
      - next
      - next-major
      - beta
      - alpha
      - "[0-9]+.[0-9]+.x"
      - "[0-9]+.x"

jobs:
  release:
    if: github.repository == 'casbin-rs/casbin-rust-cli'
    uses: casbin-rs/semantic-release-action-rust/.github/workflows/release-binary.yml@master
    secrets:
      cargo-registry-token: ${{ secrets.CARGO_TOKEN }}